### ISSUE TITLE
MPAS atmosphere tau profiling

### ISSUE THREAD

**Issue by aoyulong** [MPAS-Dev/MPAS-Model#10]
I turn on the TAU  by typing the command that is :make gfortran CORE=init_atmosphere TAU=true. And after run the ./init_atmosphere_model, I get the profile.0.0.0. Then I print it by pprof and I get some information. However, the information is all about MPI_XXXX calls. But I want profiling other different function calls of the program  besides the MPI_XXXX calls. Is there anything wrong ?
The profile information is below:

![qq20140510114831](https://cloud.githubusercontent.com/assets/3069790/2935190/21678e94-d7f6-11e3-9343-98c78ad02c00.png)
![qq20140510114903](https://cloud.githubusercontent.com/assets/3069790/2935191/286043a8-d7f6-11e3-81d2-f39ea71d92de.png)

**Comment by mgduda** [comment]
Most of us who develop MPAS-Atmosphere have little experience with Tau at present. And, since this issue is more than 4 years old (as of September 2018), I'll go ahead and close it.
