### ISSUE TITLE
FATAL ERROR: data in update host clause was not found on device 1: name=areacell

### ISSUE THREAD

**Issue by rabbanidu93** [MPAS-Dev/MPAS-Model#1006]
Dear concern,

I have compiled MPAS-A 6xx-openacc with PGI compiler using Nvidia-hpc sdk 22.9 (in GPU nvidia 2080 super). In model integration section, when i run "mpiexec -n 4 ./atmosphere_model", I am getting following error,
FATAL ERROR: data in update host clause was not found on device 1: name=areacell
file:/hdd/rabbani/MPAS-A-PGI-OACC/MPAS-Model/src/core_atmosphere/physics/mpas_atmphys_driver_sfclayer.F driver_sfclayer line:962
I have attached all namelists & log files.

Why does this problem occur? How to solve it?

Thanks in advance.
[streams.atmosphere.txt](https://github.com/MPAS-Dev/MPAS-Model/files/9979347/streams.atmosphere.txt)
[namelist.atmosphere.txt](https://github.com/MPAS-Dev/MPAS-Model/files/9979348/namelist.atmosphere.txt)
[mpirun.log](https://github.com/MPAS-Dev/MPAS-Model/files/9979349/mpirun.log)
[log.atmosphere.role03.0000.out.txt](https://github.com/MPAS-Dev/MPAS-Model/files/9979350/log.atmosphere.role03.0000.out.txt)
uname -a:
Linux gpupc 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mgduda** [comment]
I see that you've already posted this on the forum at https://forum.mmm.ucar.edu/threads/fatal-error-data-in-update-host-clause-was-not-found-on-device-1-name-areacell.12128/ . In general, the forum is the correct place to ask these sorts of questions.
