### ISSUE TITLE
In situ analysis of MPAS Atmospheric

### ISSUE THREAD

**Issue by MuzafarWani** [MPAS-Dev/MPAS-Model#1008]
I want to add VisIt or Paraview code to MPAS Atmospheric code for in situ visualization. I need to know the code location where output variables are populated in the code. Can you please point out the code location where it happens?

**Comment by mgduda** [comment]
Could you please post this question to the WRF/MPAS-A forum (https://forum.mmm.ucar.edu/)? There's a section of the forum for MPAS-A code developement discussions: https://forum.mmm.ucar.edu/forums/code-development.127/ .
