### ISSUE TITLE
Problem of processing the static field

### ISSUE THREAD

**Issue by yuemaaa** [MPAS-Dev/MPAS-Model#101]
Hi, everyone
After compiling the MPAS init_atmosphere and atmosphere cores, i try to run example 'supercell'.
make a new directory
`mkdir supercell`
down load the package
`wget http://www2.mmm.ucar.edu/projects/mpas/test_cases/v5.1/supercell.tar.gz
tar zxvf supercell.tar.gz
cd supercell`
link to init_atmosphere_model
`ln -s $MPAS/MPAS-Model/init_atmosphere_model`
process the static field
`./init_atmosphere_model`
and get an error
`Segmentation fault(core dumped)`

**file `log.init_atmosphere.0000.out` writes**
----------------------------------------------------------------------
Beginning MPAS-init_atmosphere Output Log File for task       0 of       1
    Opened at 2018/10/21 18:32:34
----------------------------------------------------------------------

 
 Using default double-precision reals
 
 Reading namelist from file namelist.init_atmosphere
 *** Encountered an issue while attempting to read namelist record data_sources
     The following values will be used for variables in this record:
 
         config_geog_data_path = /glade/p/work/wrfhelp/WPS_GEOG/
         config_met_prefix = CFSR
         config_sfc_prefix = SST
         config_fg_interval = 86400
         config_landuse_data = USGS
         config_topo_data = GTOPO30
         config_use_spechumd = F
 
 *** Encountered an issue while attempting to read namelist record vertical_grid
     The following values will be used for variables in this record:
 
         config_ztop = 30000.0000000000
         config_nsmterrain = 1
         config_smooth_surfaces = T
         config_dzmin = 0.300000000000000
         config_nsm = 30
         config_tc_vertical_grid = T
 
 *** Encountered an issue while attempting to read namelist record interpolation_control
     The following values will be used for variables in this record:
 
         config_extrap_airtemp = linear
 
 *** Encountered an issue while attempting to read namelist record preproc_stages
     The following values will be used for variables in this record:
 
         config_static_interp = T
         config_native_gwd_static = T
         config_gwd_cell_scaling = 1.00000000000000
         config_vertical_grid = T
         config_met_interp = T
         config_input_sst = F
         config_frac_seaice = T
 
 *** Encountered an issue while attempting to read namelist record io
     The following values will be used for variables in this record:
 
         config_pio_num_iotasks = 0
         config_pio_stride = 1
 
 *** Encountered an issue while attempting to read namelist record decomposition
     The following values will be used for variables in this record:
 
         config_block_decomp_file_prefix = x1.40962.graph.info.part.
         config_number_of_blocks = 0
         config_explicit_proc_decomp = F
         config_proc_decomp_file_prefix = graph.info.part.
 
 Reading streams configuration from file streams.init_atmosphere
 Found mesh stream with filename template supercell_grid.nc
 Using default io_type for mesh stream
  ** Attempting to bootstrap MPAS framework using stream: input
 Bootstrapping framework with mesh fields from input file 'supercell_grid.nc'
WARNING: Attribute file_id not found in supercell_grid.nc
WARNING:   Using '' for the previous file_id.
WARNING: Attribute parent_id not found in supercell_grid.nc
WARNING:   Setting parent_id to ''
WARNING: Attribute mesh_spec not found in supercell_grid.nc
WARNING:   Setting mesh_spec to '0.0'
WARNING: is_periodic attribute not found in supercell_grid.nc
WARNING:    Setting is_periodic to .false.
 
Parsing run-time I/O configuration from streams.init_atmosphere ...
 
 -----  found immutable stream "input" in streams.init_atmosphere  -----
         filename template:  supercell_grid.nc
         filename interval:  none
         direction:          input
         reference time:     initial_time
         record interval:    -
         input alarm:        initial_only
 
 -----  found immutable stream "output" in streams.init_atmosphere  -----
         filename template:  supercell_init.nc
         filename interval:  none
         direction:          output
         reference time:     initial_time
         record interval:    -
         output alarm:       initial_only
         package:            initial_conds

 
 -----  found immutable stream "surface" in streams.init_atmosphere  -----
         filename template:  not_needed_for_supercell
         filename interval:  none
         direction:          output
         reference time:     initial_time
         record interval:    -
         output alarm:       86400
         package:            sfc_update

 
 ----- done parsing run-time I/O from streams.init_atmosphere -----

  ** Validating streams
 
 
 Reading dimensions from input streams ...
 
 ----- reading dimensions from stream 'input' using file supercell_grid.nc
        nCells = 28080
        nEdges = 84240
        nVertices = 56160
        TWO = 2
        maxEdges = 6
        maxEdges2 = 12
        vertexDegree = 3
 
 ----- done reading dimensions from input streams -----
 
 
 Processing decomposed dimensions ...
 
  ----- done processing decomposed dimensions -----
 
 
 Assigning remaining dimensions from definitions in Registry.xml ...
        THREE = 3
        FIFTEEN = 15
        TWENTYONE = 21
        R3 = 3
        nVertLevels = 40 (config_nvertlevels)
        nSoilLevels = 4 (config_nsoillevels)
        nFGLevels = 38 (config_nfglevels)
        nFGSoilLevels = 4 (config_nfgsoillevels)
        nVertLevelsP1 = 41
        nMonths = 12 (config_months)
 
  ----- done assigning dimensions from Registry.xml -----

and gdb the core says
`#0 0x000055963e735c8e in box_rearrange_create ()`

How could i process a static field?

**Comment by mgduda** [comment]
Generally, requests for help in running either the `atmosphere` or `init_atmosphere` cores might be better suited to the support forum at http://forum.mmm.ucar.edu/phpBB3/ . Would you be willing to post this in the "MPAS-Atmosphere Support" section of the forum?
