### ISSUE TITLE
A few questions for MODEL running

### ISSUE THREAD

**Issue by dinghao1995** [MPAS-Dev/MPAS-Model#1045]
As a new user of the MPAS-O model from Asia, I have a few questions for you developers: 1. Currently, I use the data provided by MPAS official website to run MPAS-O model, such as EC60to30 or RRS30to10(https://mpas-dev.github.io/), but I don't know how these data are produced, so I would like to ask what is the source of these data? How do you make these data? 2. I also run MPAS-A model, which can be combined with WPS(pre-processing program of WRF model) and driven by FNL data; So what I want to know is, can MPAS-O model also be driven by global reanalysis data similar to FNL like MPAS-A model? If so, how to achieve it? 3. If the previous problem cannot be realized, how to prepare the data source? And how do I modify the *init file (namelist and streams) to make the driver fields for MPAS-O models?

**Comment by 1JunGu** [comment]
about ocean component of MPAS, I think you should ask E3SM project for further advice. Now this project is maybe mainly intended for MPAS-Atmosphere. Besides, the code is open and reading the code is more useful.
2023年4月17日 +0800 22:15 DING ***@***.***>，写道：
