### ISSUE TITLE
Build error for ocean core

### ISSUE THREAD

**Issue by daniloceano** [MPAS-Dev/MPAS-Model#1046]
Hello,

Make is failing for the OCEAN core:

![image](https://user-images.githubusercontent.com/56005607/232782894-834f483a-dab3-4fb5-a6a5-e61bd92f881b.png)

Here is the full log:
[log_build_ocean.txt](https://github.com/MPAS-Dev/MPAS-Model/files/11261858/log_build_ocean.txt)

- Compilers used:
export SERIAL_FC=gfortran
export SERIAL_F77=gfortran
export SERIAL_CC=gcc
export SERIAL_CXX=g++
export MPI_FC=mpifort
export MPI_F77=mpifort
export MPI_CC=mpicc
export MPI_CXX=mpic++

- Versions: 
gcc version: 5.4.0
MPICH version 3.3.1

- NetCDF
netcdf library version 4.7.0

- Parallel NetCDF
PnetCDF Version:   1.11.2

- PIO: 2 (couldn't find a way to check that but atmosphere_model was compiled using the flag USE_PIO2=true)

- uname -a
Linux nemo 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- make line used to build the executable:
make -j4 gfortran CORE=ocean PRECISION=double Debug=true USE_PIO2=true > log_build_ocean.txt

Any help is appreciated

**Comment by mgduda** [comment]
MPAS-Ocean is now being developed within the [E3SM](https://github.com/E3SM-Project/E3SM) repository.
