### ISSUE TITLE
MPAS-O init run

### ISSUE THREAD

**Issue by dinghao1995** [MPAS-Dev/MPAS-Model#1056]
Hello,
When I use MPAS-O model and make a "init" run (config_ocean_run_mode = 'init'), I used the **_MERCATOR GLORYS12V1_** and **_ETOPO_** dataset for driving. Here are some of my Settings:
&global_ocean
    config_global_ocean_minimum_depth = 15
    config_global_ocean_depth_file = 'out_data_02.nc'
    config_global_ocean_depth_dimname = 'depth'
    config_global_ocean_depth_varname = 'depth'
    config_global_ocean_depth_conversion_factor = 1.0
    config_global_ocean_temperature_file = 'out_data_02.nc'
    config_global_ocean_salinity_file = 'out_data_02.nc'
    config_global_ocean_temperature_varname = 'thetao'
    config_global_ocean_salinity_varname = 'so'
    config_global_ocean_tracer_nlat_dimname = 'latitude'
    config_global_ocean_tracer_nlon_dimname = 'longitude'
    config_global_ocean_tracer_ndepth_dimname = 'depth'
    config_global_ocean_tracer_depth_conversion_factor = 1.0
    config_global_ocean_tracer_vert_levels = 50
    config_global_ocean_tracer_latlon_degrees = .true.
    config_global_ocean_tracer_lat_varname = 'latitude'
    config_global_ocean_tracer_lon_varname = 'longitude'
    config_global_ocean_tracer_depth_varname = 'depth'
    config_global_ocean_tracer_method = 'bilinear_interpolation'
--------------------------------------------------------------------------------------------------------
    config_global_ocean_topography_file = 'ETOPO_2022_v1_60s_N90W180_bed.nc'
    config_global_ocean_topography_nlat_dimname = 'lat'
    config_global_ocean_topography_nlon_dimname = 'lon'
    config_global_ocean_topography_latlon_degrees = .true.
    config_global_ocean_topography_lat_varname = 'lat'
    config_global_ocean_topography_lon_varname = 'lon'
    config_global_ocean_topography_varname = 'z'
    config_global_ocean_topography_has_ocean_frac = .false.
    config_global_ocean_topography_ocean_frac_varname = 'none'
    config_global_ocean_topography_method = 'bilinear_interpolation'
    config_global_ocean_smooth_topography = .true.
    config_global_ocean_deepen_critical_passages = .true.
    config_global_ocean_depress_by_land_ice = .false.
    config_global_ocean_land_ice_topo_file = 'ETOPO_2022_v1_60s_N90W180_surface.nc'
    config_global_ocean_land_ice_topo_nlat_dimname = 'lat'
    config_global_ocean_land_ice_topo_nlon_dimname = 'lon'
    config_global_ocean_land_ice_topo_latlon_degrees = .true.
    config_global_ocean_land_ice_topo_lat_varname = 'lat'
    config_global_ocean_land_ice_topo_lon_varname = 'lon'
    config_global_ocean_land_ice_topo_thickness_varname = 'z'
    config_global_ocean_land_ice_topo_draft_varname = 'none'
    config_global_ocean_land_ice_topo_ice_frac_varname = 'none'
    config_global_ocean_land_ice_topo_grounded_frac_varname = 'none'
----------------------------------------------------------------------------------------------------------
But there are errors here:
CRITICAL ERROR: could not open file out_data_02.nc
Then I checked the 'mpas_ocn_init_global_ocean.F' file:

vi src/core_ocean/mode_init/mpas_ocn_init_global_ocean.F
inputFile = MPAS_io_open(config_global_ocean_depth_file, MPAS_IO_READ, MPAS_IO_NETCDF, iocontext_ptr, ierr=iErr)
      if (iErr .ne. 0) then
         call mpas_log_write( 'could not open file '// trim(config_global_ocean_depth_file), MPAS_LOG_CRIT)
         return
      end if

Are there any requirements for the format of the netCDF file?

**Comment by mgduda** [comment]
MPAS-Ocean is now being developed within the [E3SM](https://github.com/E3SM-Project/E3SM) repository.
