### ISSUE TITLE
can intel MPI+openmp hybrid mode be implemented on MPAS software?

### ISSUE THREAD

**Issue by jackhou0205** [MPAS-Dev/MPAS-Model#1114]
The title above should be a 1 line short summary of the issue.

Enter a description of the issue.
This should include what the symptoms are, and steps to reproduce.

Additionally please enter this information if applicable:
 - Compiler and version
 - MPI implementation and version
 - NetCDF version
 - Parallel NetCDF version
 - Parallel IO version
 - Output of `uname -a`
 - The make line used to build the executable
 - The line used to run the executable
 - Test case used

**Comment by mgduda** [comment]
Please use the WRF/MPAS forum at https://forum.mmm.ucar.edu/ to ask these sorts of questions.
