### ISSUE TITLE
Surface low value area in MPAS-O

### ISSUE THREAD

**Issue by dinghao1995** [MPAS-Dev/MPAS-Model#1146]
In MPAS-O simulation results, why are there abnormally low areas of surface temperature and salinity?

![20b97136da008bd0f6cad0b2abaa951](https://github.com/MPAS-Dev/MPAS-Model/assets/37833117/453de986-ceec-4a88-bb81-06d06d15d358)
![30ed1ec6b35e0a9b1d48e19bf96e210](https://github.com/MPAS-Dev/MPAS-Model/assets/37833117/7c1066ad-6393-4e33-a249-7c1d5a76d3e6)

**Comment by mgduda** [comment]
MPAS-Ocean is now being developed within the [E3SM](https://github.com/E3SM-Project/E3SM) repository.
