### ISSUE TITLE
compiling error with ifort

### ISSUE THREAD

**Issue by zpmaths** [MPAS-Dev/MPAS-Model#12]
The error message is as bellow:

mpif90 -DLANL_FORMULATION -D_MPI -DUNDERSCORE -Dmpas  -real-size 64 -O3 -convert big_endian -FR  -c mpas_atmphys_lsm_noahinit.F -I/home/zp/local/netcdf/include -I/home/zp/local/pio/include -I/home/zp/local/parallel-netcdf/include -I/home/zp/local/netcdf/include -I/home/zp/local/pio/include -I/home/zp/local/parallel-netcdf/include -I../../framework -I../../operators -I./physics_wrf -I../../external/esmf_time_f90 
mpas_atmphys_lsm_noahinit.F(23): error #6581: Unresolved rename.   [GRAV]
 use mpas_atmphys_constants, grav => g
-----------------------------^
mpas_atmphys_lsm_noahinit.F(146): error #6498: The use-name for this local-name is not defined.   [GRAV]
                fk = (((hlice/(grav_(-psisat))) \* &
-------------------------------^
compilation aborted for mpas_atmphys_lsm_noahinit.F (code 1)
make[4]: *_\* [mpas_atmphys_lsm_noahinit.o] Error 1
make[4]: Leaving directory `/home/zp/MPAS-Release-2.0/src/core_atmosphere/physics'
make[3]: *** [physcore] Error 2
make[3]: Leaving directory`/home/zp/MPAS-Release-2.0/src/core_atmosphere'
make[2]: **\* [dycore] Error 2
make[2]: Leaving directory `/home/zp/MPAS-Release-2.0/src'
make[1]: *** [mpas_main] Error 2
make[1]: Leaving directory`/home/zp/MPAS-Release-2.0'
make: **\* [ifort] Error 2

my ifort compiler version is 14.0.0.
BTW,I can build MPAS-A sucessfully with gfortran(4.4.7),but when i turned to ifort,the error above happened.Does anyone know how to fix it?

**Comment by mgduda** [comment]
As far as I'm aware, this issue has been resolved in recent releases of MPAS-Atmosphere, so I'll close this issue.
