### ISSUE TITLE
output_interval not getting carried through to stream defaults

### ISSUE THREAD

**Issue by jonwoodring** [MPAS-Dev/MPAS-Model#16]
This is in reference to my recent [Okubo Weiss 3.3](https://github.com/jonwoodring/MPAS-Release/compare/okubo-weiss-3.3) pull request.

In [Registry_okubo_weiss.xml](https://github.com/jonwoodring/MPAS-Release/blob/aab94cd7841d6eef6e309627af31064f5e318d5a/src/core_ocean/analysis_members/Registry_okubo_weiss.xml), the _output_interval_ parameter for the "okuboWeissOutput" stream is not being carried to the streams.ocean_forward.defaults after compilation.

I tried putting it in different positions, but in each case it was not being copied to the defaults file after compilation.

**Comment by douglasjacobsen** [comment]
@jonwoodring that is because the type of the stream is set to `type="none"`. This implies that the stream shouldn't have any intervals. In the future we'll likely have a different way of handling this, but for now if you want an interval carried through, it has to have a type that matches the interval (i.e. type="input" for input_interval).

**Comment by jonwoodring** [comment]
I had set it to "none" from advice of @mark-petersen, because we agreed it shouldn't be output by default, but I wanted to set some output_interval defaults in case someone did turn it on.

**Comment by douglasjacobsen** [comment]
Yeah, that's a sensible thing to do. It's just the translation from Registry.xml to streams.ocean_forward currently only transfers intervals for streams that share the same time.

This will probably be changed before our next release though.

**Comment by jonwoodring** [comment]
Hmm. OK. 

So, doing the first case, putting scratch variables inside of *var_struct name="amOkuboWeiss"* failed with this message:

> Reading registry file from standard input
> ERROR: Packages attribute not allowed on scratch variable thresholdedOkuboWeiss in var_struct amOkuboWeiss.

For the second case, putting the variables inside of "scratch," I'm finding it to work now at least with 16 cores. I'm scaling it up now to see if it crashes at a higher core count. I will let you know if it works.

Though, when I originally tried it, it was based off the 3.2 and I hadn't incorporated 3.3 hotfixes yet. Would there have been something that fixed it since 3.2 to 3.3?

**Comment by mark-petersen** [comment]
This issue has gone stale. Closing.
