### ISSUE TITLE
Dependencies of a proposed compass conda environment

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#166]
Packages:
- [ ] mpas_mesh_tools (https://github.com/MPAS-Dev/MPAS-Tools/pull/248):
  - [x] mesh conversion tools (https://github.com/MPAS-Dev/MPAS-Tools/pull/243)
  - [ ] `mark_horns_for_culling.py` (?) (https://github.com/MPAS-Dev/MPAS-Tools/pull/249)
  - [x] planar hex (https://github.com/MPAS-Dev/MPAS-Tools/pull/246)
  - [ ] 4 scripts from landice mesh tools (https://github.com/MPAS-Dev/MPAS-Tools/pull/249): 
    - [ ] `create_landice_grid_from_generic_MPAS_grid.py`
    - [ ] `define_cullMask.py`
    - [ ] `interpolate_to_mpasli_grid.py`
    - [ ] `mark_domain_boundaries_dirichlet.py`
  - [ ] planar mesh transformation tools
    - [ ] `translate_planar_grid.py`
    - [ ] ...
  - [ ] ...
- [ ] geometric_features (https://github.com/MPAS-Dev/geometric_features/pull/102)
- [x] metis
- [x] jigsaw (https://github.com/xylar/staged-recipes/tree/jigsaw/recipes/jigsaw)
- [ ] jigsaw-geo-matlab?
- [ ] ...

**Comment by xylar** [comment]
This issue is meant to help me, @mark-petersen, @matthewhoffman and other keep track of the process of creating a conda environment for setting up and running COMPASS test cases.  The conda environment is supposed to make it easier to set up and keep track of the dependencies (geometric features, mesh conversion tools, etc.) that are required to build COMPASS test cases so that relative non-experts can get started more easily.

**Comment by xylar** [comment]
@matthewhoffman, it doesn't look like we use `mark_horns_for_culling.py` in ocean COMPASS.  I didn't see int in land-ice COMPASS either.  Do you use it elsewhere and it is worth including in `mpas_mesh_tools`?

**Comment by xylar** [comment]
@mark-petersen and @pwolfram, can you help me figure out what Jigsaw related tools need to go into `mpas_mesh_tools`?

**Comment by xylar** [comment]
@dengwirda, it would be great to have a conversion at the March E3SM meeting (if not before) about what the path would be to getting the necessary Jigsaw tools themselves in a form where they could be part of the conda environment.

**Comment by dengwirda** [comment]
@xylar I'm trying to make my way through `COMPASS` at present, so it's a good time to work on this I think. (For the non-conda proficient) what details do you need in terms of `JIGSAW`? There are no external dependencies involved, and the build process is essentially a one-liner with `g++`...

I'll be at the E3SM meeting next month, but it'd be great to work on this over the coming weeks. I'd like to get a better understanding of the overall framework myself, and to streamline the `JIGSAW` integration aspects.

**Comment by xylar** [comment]
@dengwirda, thanks for the feedback.

I would be eager to make a conda-forge recipe for JIGSAW with your permission.  This would build and distribute JIGSAW automatically as part of any conda environment that listed `jigsaw` as a dependency or someone could ask for it explicitly with something like:
```
conda create -n jigsaw -c conda-forge jigsaw
conda activate jigsaw
```
This would create a virtual environment called `jigsaw` with the `jigsaw` package installed in it and activate that virtual environment.  All jigsaw commands (maybe there's only one) would then be available.

What I would need from you is for you to make a tag or release of the code that I can point to.  I looked at https://github.com/dengwirda/jigsaw and didn't see any yet.  It's possible but considered very bad form to point to a specific commit on GitHub and build a package from it.  The reason is that there could be confusion about which commit corresponds to a given version of JIGSAW unless you explicitly tag it.

If you make a tag, I'll put together a recipe for building JIGSAW and get your approval before it goes live. 
 Thanks for your help!

**Comment by xylar** [comment]
@mark-petersen, I could use your help figuring out which scripts from MPAS-Tools are needed somewhere in COMPASS.  I need this list to update https://github.com/MPAS-Dev/MPAS-Tools/pull/248 to include all these tools so we don't need to have the COMPASS user check out MPAS-Tools.

**Comment by xylar** [comment]
The compass python environment is settled and can be constructed with these instructions: 
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/README_ocean.md
