### ISSUE TITLE
JIGSAW-produced meshes not BFB reproducable

### ISSUE THREAD

**Issue by sbrus89** [MPAS-Dev/MPAS-Model#178]
Meshes produced with the JIGSAW workflow vary between runs. This is most likely due to using an approximate nearest neighbor search to find the distances to the coastline which are then used to specify resolution input to JIGSAW.

**Comment by sbrus89** [comment]
Here's the module import:
https://github.com/MPAS-Dev/MPAS-Model/blob/0040864d4a2c16d7268af8eb644c6bd1ed24f313/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py#L11

Here's where the search object is created:
https://github.com/MPAS-Dev/MPAS-Model/blob/0040864d4a2c16d7268af8eb644c6bd1ed24f313/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py#L452-L456

Here's where the distances are computed:
https://github.com/MPAS-Dev/MPAS-Model/blob/0040864d4a2c16d7268af8eb644c6bd1ed24f313/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py#L469

**Comment by xylar** [comment]
Thanks @sbrus89.  I'm going to see if I can figure out how to set the random seed to a fixed value.  @jonbob has complained as well about the lack of reproducibility.  It means a lot of pointless regeneration of mapping files.

**Comment by xylar** [comment]
Reading the pyflann code:
https://github.com/mariusmuja/flann/blob/master/src/python/pyflann/index.py#L88
The random seed is omitted.  According to [numpy documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState):

> If seed is None, then RandomState will try to read data from /dev/urandom (or the Windows analogue) if available or seed from the clock otherwise.

The fix should be as simple as calling:
```
flann = pyflann.FLANN()
flann.__rn_gen.seed(0)
flan.build_index(
...
```

@sbrus89, could you try this and let me know how it goes?  It should be easy to tell if you're getting bit-for-bit results out of the very beginning of the process where you use `pyflann`.

**Comment by sbrus89** [comment]
@xylar, Thanks for looking into this. I feel bad that this has created extra work for @jonbob. It seems like your suggestion should fix the issue. I'll test and let you know what happens.

**Comment by xylar** [comment]
Didn't work.

Let's try
```python
 flann.build_index( 
     coast_pts_xyz, 
     algorithm='kdtree', 
     target_precision=1.0,
     random_seed=0)
...
idx, d = flann.nn_index(pts, checks=2000, random_seed=0)
```

**Comment by sbrus89** [comment]
@xylar, that seems to work! At least the input to JIGSAW is now BFB between runs.

**Comment by xylar** [comment]
Great!  If you could test the full production on a smaller grid and make sure 2 runs produce the same final mesh, that would be tremendously helpful!

Could you also make a PR with these changes?

**Comment by sbrus89** [comment]
@xylar, I verified that the CONUS mesh was BFB in two subsequent runs. I also put in a pull request (#180).
