### ISSUE TITLE
COMPASS python3 transition

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Model#213]
Python 2 support is fading across the community and our COMPASS scripts are not python 3 compliant.

Is it worth updating COMPASS to be entirely python 3 supporting?

**Comment by xylar** [comment]
If you mean should we drop python 2 support and go to python 3 only, I don't think that's a good idea.  It would mean every script would have to be transitioned to python 3 all at once, whereas supporting both will allow a more gradual port.

**Comment by xylar** [comment]
By the way, at least some COMPASS scripts do support python 3 as of:
https://github.com/MPAS-Dev/MPAS-Model/pull/177

Also, there's a JIRA epic that I'm in charge of for converting the rest of COMPASS to support python 3.

**Comment by xylar** [comment]
I believe this issue is largely redundant with #132 so I'm going to close it.
