### ISSUE TITLE
Missing script referenced in COMPASS Ocean

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#220]
A script, `mesh_comparison.py` is referenced in COMPASS's new `globa_ocean` test cases:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/global_ocean/config_files/config_mesh_metrics.xml#L7

This file is pointing to `MPAS-Tools/mesh_tools/mesh_comparison.py`, but there doesn't seem to be any such file:
https://github.com/MPAS-Dev/MPAS-Tools/tree/master/mesh_tools

A little sleuthing suggests it's here:
https://github.com/sbrus89/MPAS-Tools/blob/jigsaw_mesh_creation/mesh_tools/mesh_comparison.py
but hasn't been merged and I didn't see a PR.

@sbrus89, is the solution to add this tool?  Or to remove reference to it from COMPASS for now?

**Comment by sbrus89** [comment]
@xylar, Thanks for bringing this up. I don't think the script is ready to be merged at the moment. (It has paths that are hard-coded etc.) My feeling is that we should probably remove the reference for now. It should never have made it in without having the tool merged. Sorry about that.

**Comment by xylar** [comment]
Okay, no problem.  I'll remove it as part of a bigger commit I'm working on.
