### ISSUE TITLE
PIO error when procs = 1024

### ISSUE THREAD

**Issue by raycao88124** [MPAS-Dev/MPAS-Model#23]
Hi,

```
I was trying to run MPAS with 1024 processes using 128 machines.  During init state for domain, I got this error: 
```

 box_rearrange::compute_dest:: INFO io          349  start=                    1              1895877  count=                   40                 5448
 box_rearrange::compute_dest:: INFO io          350  start=                    1              1901325  count=                   40                 5448
 box_rearrange::compute_dest:: INFO io          351  start=                    1              1906773  count=                   40                 5448
 box_rearrange::compute_dest:: INFO io          352  start=                    1              1912221  count=                   40                 5448
 box_rearrange.F90.in         752        1005                    0              5509783                    0              5469764                   40              5475212
 box_rearrange.F90.in         752        1006                    0              5509783                    0              5475212                   40              5480660
 box_rearrange::compute_dest:: ERROR: no destination found for compdof=            220391321
 box_rearrange::compute_dest:: INFO: gsize=          40     5578724
 box_rearrange::compute_dest:: INFO: nioproc        1024  ioproc          555  ioindex                    -1

The error output is actually way more but I believe these few lines show the actual error. 
I think this is related to the PIO library? I am currently using PIO1.7.2

Thanks,
Lei

**Comment by mgduda** [comment]
@raycao88124 , which MPAS core (model) are you running, and which mesh are you using? Are you able to successfully run using other MPI task counts, i.e., is it only 1024 tasks that fails?

**Comment by xylar** [comment]
@raycao88124, is this still an outstanding issue for you?  If so, feel free to re-open this issue and provide more information.  For now, I am closing the issue because we don't have sufficient information to provide any assistance and there has been no update in several months.
