### ISSUE TITLE
Consider using Basemap for 2D interpolation

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#238]
In several COMPASS scripts, scipy's interpolation infrastructure is used to perform 2D interpolation.  I have found scipy to be very slow and memory intensive for this purpose.  A somewhat buried alternative is in basemap's [interp()](https://matplotlib.org/basemap/api/basemap_api.html#mpl_toolkits.basemap.interp), which I have found to be much faster and more memory efficient.

Here are the places where I would foresee making the change:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS/inject_bathymetry.py#L65-L66
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS/inject_bathymetry.py#L85-L86
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS/inject_meshDensity.py#L44-L45

This is obviously not a high priority item but it seems like these interpolation steps contribute a significant fraction of the time it currently takes to generate an MPAS mesh.

**Comment by sbrus89** [comment]
@xylar, Thanks for pointing out this alternative. I'd be happy to update the scripts at some point. Finding something fast and more memory efficient would be great. Just one question: Is there support for basemap in python 3? I remember you mentioning something about moving away from basemap as we head toward python 3.

**Comment by xylar** [comment]
> Is there support for basemap in python 3?

Yes, there is.  The problem with basemap isn't related to python 3.  It's to do with not developing it further.  But that definitely *is* a problem.  For most purposes, I've been pointing folks toward cartopy, but it's not quite there yet either.  And I'm not aware of a similar interpolation function in cartopy, though it's likely to be in there somewhere.  I'll take a quick look.

**Comment by xylar** [comment]
A quick search didn't turn up anything as a satisfying alternative.

**Comment by xylar** [comment]
I'm going to close this.  It's been considered and found non-optimal...
