### ISSUE TITLE
Automatically download bathymetry data

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#240]
The following COMPASS ocean config files use the bathymetry data set `SRTM15_plus/earth_relief_15s.nc`:
* `ocean/global_ocean/NAEC60to30cr8L60/init/config_base_mesh.xml`
* `ocean/global_ocean/config_files/config_mesh_metrics.xml`
* `ocean/global_ocean/USDEQU300cr20rr3/init/config_base_mesh.xml`
* `ocean/global_ocean/NAEC60to30cr8/init/config_base_mesh.xml`
* `ocean/global_ocean/USDEQU120cr10rr1/init/config_base_mesh.xml`
* `ocean/coastal/USDEQU120cr10rr2/build_mesh/config_culled_mesh.xml`
* `ocean/coastal/USDEQU120cr10rr2/build_mesh/config_base_mesh.xml`

Currently, there is no way for a user not on LANL IC to get this file.  If we have permission, it should be put on `oceans11` and each of these scripts needs a line like:
```
	<get_file dest_path="bathymetry_database" file_name="SRTM15_plus/earth_relief_15s.nc">
		<mirror protocol="wget" url="http://oceans11.lanl.gov/mpas_data/bathymetry_database/"/>
	</get_file>
```
(I'm not sure the subdirectory will be handled correctly so it might be better not to not put it in a subdirectory.)

If we can't disribute the file ourselves but it is available elsewhere on the web, it should be possible to put in a line like the one above in each config file with the URL to the data set.  Searching around the web, I found this URL but a file with the name `earth_relief_15s.nc` is not available there: [ftp://topex.ucsd.edu/pub/srtm15_plus/](ftp://topex.ucsd.edu/pub/srtm15_plus/)

**Comment by xylar** [comment]
I put a copy of the `bathymetry_database` here on IC:
```
bathymetry_database = /usr/projects/regionalclimate/COMMON_MPAS/ocean/grids/bathymetry_database
```
I think this is more appropriate than having it in a user's space.

**Comment by sbrus89** [comment]
@xylar, I agree we need to clear this up. I've overlooked the issue for too long now.
