### ISSUE TITLE
test cases failing (1-4)

### ISSUE THREAD

**Issue by rphani** [MPAS-Dev/MPAS-Model#25]
Hi,

I am trying to understand the dynamical core of the MPAS model and trying to run the test cases. I could run supercell and Mountain wave (cases 5,6) easily but having trouble with the 1-4 test cases where I am encountering with floating-point error and core dumps. Below are the errors. Is this error something to do with the flags or single/double precision? The have tried with 1-4 cases with the case 5 and 6 executables as both of them differ.

Test-1 error
========================================================
  grid metrics setup complete 
 MAX U wind before REBALANCING ---->   34.9849780606604     
 MAX U wind after REBALANCING ---->   34.9990526152960     
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source             
init_atmosphere_m  000000000123B615  Unknown               Unknown  Unknown
init_atmosphere_m  0000000001239237  Unknown               Unknown  Unknown
init_atmosphere_m  00000000011E7294  Unknown               Unknown  Unknown
init_atmosphere_m  00000000011E70A6  Unknown               Unknown  Unknown
init_atmosphere_m  000000000117A0E6  Unknown               Unknown  Unknown
init_atmosphere_m  000000000117E4B6  Unknown               Unknown  Unknown
libpthread.so.0    00002AB2D30D8790  Unknown               Unknown  Unknown
init_atmosphere_m  00000000007B2CCE  init_atm_cases_mp        1009  mpas_init_atm_cases.F
init_atmosphere_m  0000000000764B55  init_atm_cases_mp         121  mpas_init_atm_cases.F
init_atmosphere_m  0000000000763499  init_atm_core_mp_          81  mpas_init_atm_core.F
init_atmosphere_m  0000000000412ABC  mpas_subdriver_mp         326  mpas_subdriver.F
init_atmosphere_m  000000000040E7DA  MAIN__                     16  mpas.F
init_atmosphere_m  000000000040E75E  Unknown               Unknown  Unknown
libc.so.6          00002AB2D3588D5D  Unknown               Unknown  Unknown
init_atmosphere_m  000000000040E669  Unknown               Unknown  Unknown
========================================================

Test-4 error
========================================================
 WARNING: File 
  squall line - super cell test case 
  squall line test case
  calling test case setup 
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source             
init_atmosphere_m  000000000123B615  Unknown               Unknown  Unknown
init_atmosphere_m  0000000001239237  Unknown               Unknown  Unknown
init_atmosphere_m  00000000011E7294  Unknown               Unknown  Unknown
init_atmosphere_m  00000000011E70A6  Unknown               Unknown  Unknown
init_atmosphere_m  000000000117A0E6  Unknown               Unknown  Unknown
init_atmosphere_m  000000000117DFA7  Unknown               Unknown  Unknown
libpthread.so.0    00002B33654FC790  Unknown               Unknown  Unknown
init_atmosphere_m  000000000122C8FB  Unknown               Unknown  Unknown
init_atmosphere_m  000000000122C387  Unknown               Unknown  Unknown
init_atmosphere_m  000000000122C357  Unknown               Unknown  Unknown
init_atmosphere_m  000000000092DDAD  atm_advection_mp_         543  mpas_atm_advection.F
init_atmosphere_m  000000000092D17B  atm_advection_mp_         437  mpas_atm_advection.F
init_atmosphere_m  0000000000918B10  atm_advection_mp_         147  mpas_atm_advection.F
init_atmosphere_m  00000000007D7D5E  init_atm_cases_mp        1398  mpas_init_atm_cases.F
init_atmosphere_m  000000000076596B  init_atm_cases_mp         143  mpas_init_atm_cases.F
init_atmosphere_m  0000000000763499  init_atm_core_mp_          81  mpas_init_atm_core.F
init_atmosphere_m  0000000000412ABC  mpas_subdriver_mp         326  mpas_subdriver.F
init_atmosphere_m  000000000040E7DA  MAIN__                     16  mpas.F
init_atmosphere_m  000000000040E75E  Unknown               Unknown  Unknown
libc.so.6          00002B33659ACD5D  Unknown               Unknown  Unknown
init_atmosphere_m  000000000040E669  Unknown               Unknown  Unknown
=======================================================

Regards,
Phani.

**Comment by mgduda** [comment]
Are you compiling with `DEBUG=true`? If so, do the test cases run when you clean and re-compile without this option? My first guess is that there are some otherwise harmless floating-point exceptions that are causing the code to stop when floating-point trapping is enabled by the debug build. Also, which compilers are you using?

**Comment by rphani** [comment]
Thanks. You are right, I was compiling with DEBUG=true.
Now the inti_atmosphere has run. 
I was using mpiifort.
It worked.

**Comment by xylar** [comment]
@mgduda and @rphani, can this issue be closed?

**Comment by rphani** [comment]
Yes. It can be closed.
