### ISSUE TITLE
Update CVMix after recent release with python 3 support

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#250]
A recent release of CVMix adds python 3 support:
https://github.com/CVMix/CVMix-src/releases/tag/v0.95-beta

We should point to this release to prevent build issues when using python 3.

**Comment by xylar** [comment]
@vanroekel, are you aware of changes to CVMix that we should *not* be bringing in by updating to this version?  It would be hard to imagine everything is bit-for-bit so maybe we need to be careful?

**Comment by vanroekel** [comment]
@xylar -- we have fully tested v0.94-beta in MPAS-ocean and E3SM G and B-cases and the results look good (a PR is waiting for merge to update to this tag #134).  Everything in v0.95-beta appear to be make file changes to support python 3 and so should not change results.  However, our flavor of KPP is protected in CVMix by namelist options so we should be able to retain BFB.

**Comment by xylar** [comment]
Thanks @vanroekel, this is very helpful to know.  That should mean that updating to v0.95-beta after #134 goes in should be easy.  I definitely think that's necessary before the v2 release because we will need to move that build to python 3.

**Comment by xylar** [comment]
Addressed by #251
