### ISSUE TITLE
The atmosphere_model stuck and no results

### ISSUE THREAD

**Issue by suzhongyue** [MPAS-Dev/MPAS-Model#27]
The compilation process has been completed, and produced init_atmosphere_model and atmosphere_model file. The init_atmosphere_model file run and produced static.nc and init.nc.
When used the mesh of x1.2562.grid.nc, the output is right. My problem is no results when using mesh of x1.655362.grid.nc and x1.40962.init.nc. 

Additionally please enter this information if applicable:
 - Compiler and version
ifort and icc, 2017
 - MPI implementation and version
mpich 3.2
 - NetCDF version
netcdf 4.4.1.1
 - Parallel NetCDF version
parallel netcdf 1.8.1
 - Parallel IO version
ParallelIO 2.3.0
 - The make line used to build the executable
make ifort CORE=atmosphere USE_PIO2=true
 - The line used to run the executable
/XXX/MPAS/mpas_io/bin/mpiexec.hydra -genv I_MPI_DEVICE rdma /XXX/modelcore/MPAS/MPAS-Release-5.2/atmosphere_model
 - Test case used
CFSR:2010-10-23_00
x1.40962.init.nc

Here is the compiling information:

> export LIBSRC=XXX/MPAS_sources
>export LIBBASE=XXX
># Compilers
>export SERIAL_FC=ifort
>export SERIAL_F77=ifort
>export SERIAL_CC=icc
>export SERIAL_CXX=icpc
>export MPI_FC=mpifort
>export MPI_F77=mpifort
>export MPI_CC=mpicc
>export MPI_CXX=mpicxx
>########################################
># MPICH
>########################################
>tar xzvf ${LIBSRC}/mpich-3.2.tar.gz
>cd mpich-3.2
>export CC=$SERIAL_CC
>export CXX=$SERIAL_CXX
>export F77=$SERIAL_F77
>export FC=$SERIAL_FC
>unset F90  # This seems to be set by default on NCAR's Cheyenne and is problematic
>unset F90FLAGS
>./configure --prefix=${LIBBASE} --disable-shared
>make
>make check
>make install
>export PATH=${LIBBASE}/bin:$PATH
>cd ..
>rm -rf mpich-3.2
>########################################
># cmake
>########################################
>tar xzvf ${LIBSRC}/cmake-3.4.0-rc3.tar.gz
>cd cmake-3.4.0-rc3
>./bootstrap --prefix=${LIBBASE}
>gmake
>gmake install
>export PATH=${LIBBASE}/bin:$PATH
>cd ..
>rm -rf cmake-3.4.0-rc3
>########################################
># zlib
>########################################
>tar xzvf ${LIBSRC}/zlib-1.2.8.tar.gz
>cd** zlib-1.2.8
>./configure --prefix=${LIBBASE} --static
>make
>make install
>cd ..
>rm -rf zlib-1.2.8
>########################################
># HDF5
>########################################
>tar xjvf ${LIBSRC}/hdf5-1.8.19.tar.bz2
>cd hdf5-1.8.19
>export FC=$MPI_FC
>export CC=$MPI_CC
>export CXX=$MPI_CXX
>./configure --prefix=${LIBBASE} --enable-parallel --with-zlib=${LIBBASE} --disable-shared
>make
>make check
>make install
>cd ..
>rm -rf hdf5-1.8.19
>########################################
># Parallel-netCDF
>########################################
>tar xzvf ${LIBSRC}/parallel-netcdf-1.8.1.tar.gz
>cd parallel-netcdf-1.8.1
>export CC=$SERIAL_CC
>export CXX=$SERIAL_CXX
>export F77=$SERIAL_F77
>export FC=$SERIAL_FC
>export MPICC=$MPI_CC
>export MPICXX=$MPI_CXX
>export MPIF77=$MPI_F77
>export MPIF90=$MPI_FC
>### Will also need gcc in path
>./configure --prefix=${LIBBASE}
>make
>make testing
>make install
>export PNETCDF=${LIBBASE}
>cd ..
>rm -rf parallel-netcdf-1.8.1
>########################################
># netCDF (C library)
>########################################
>tar xzvf ${LIBSRC}/netcdf-4.4.1.1.tar.gz
>cd netcdf-4.4.1.1
>export CPPFLAGS="-I${LIBBASE}/include"
> export LDFLAGS="-L${LIBBASE}/lib"
> export LIBS="-lhdf5_hl -lhdf5 -lz -ldl"
> export CC=$MPI_CC
> ./configure --prefix=${LIBBASE} --disable-dap --enable-netcdf4 --enable-pnetcdf --enable-parallel-tests --disable-shared
> make
> make check
> make install
> export NETCDF=${LIBBASE}
> cd ..
> rm -rf netcdf-4.4.1.1
> 
> ########################################
> # netCDF (Fortran interface library)
> ########################################
> tar xzvf ${LIBSRC}/netcdf-fortran-4.4.4.tar.gz
> cd netcdf-fortran-4.4.4
> export FC=$MPI_FC
> export F77=$MPI_F77
> export LIBS="-lnetcdf ${LIBS}"
> ./configure --prefix=${LIBBASE} --enable-parallel-tests --disable-shared
> make
> make check
> make install
> cd ..
> rm -rf netcdf-fortran-4.4.4
> 
> ########################################
> # PIO
> ########################################
> tar -xvf ${LIBSRC}/ParallelIO.tar
> cd ParallelIO
> export PIOSRC=`pwd`
> cd ..
> mkdir pio
> cd pio
> export CC=mpicc
> export FC=mpifort
> cmake -DNetCDF_C_PATH=$NETCDF -DNetCDF_Fortran_PATH=$NETCDF -DPnetCDF_PATH=$PNETCDF -DCMAKE_INSTALL_PREFIX=$LIBBASE -DPIO_ENABLE_TIMING=OFF $PIOSRC
> make
> make install
> cd ..
> rm -rf pio ParallelIO
> export PIO=$LIBBASE
> ########################################
> # Other environment vars needed by MPAS
> ########################################
> export MPAS_EXTERNAL_LIBS="-L${LIBBASE}/lib -lhdf5_hl -lhdf5 -ldl -lz"
> export MPAS_EXTERNAL_INCLUDES="-I${LIBBASE}/include"

**Comment by mgduda** [comment]
@suzhongyue It may be preferable to use GitHub Issues only to report specific problems in the code. However, if you're in need of assistance, it may be better to use the MPAS-Atmosphere support forum at http://forum.mmm.ucar.edu/phpBB3/.
