### ISSUE TITLE
`config_disable_vel_coriolis` option also turns off momentum advection

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Model#291]
The option `config_disable_vel_coriolis=.false.` disables more than Coriolis forcing, but also the momentum advection term via absolute vorticity and kinetic energy, e.g., Ringler et al (2010) for `\eta` and `K`, e.g., terms in equation 4.  Ideally, we would have separate flags to distinguish between turning off Coriolis itself and momentum advection.

The place in the code where they are mixed via the `config_disable_vel_coriolis` flag, which turns into a `coriolisOn` flag (e.g., at https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_vel_coriolis.F#L130) is at https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_vel_coriolis.F#L174

**Comment by xylar** [comment]
Closed via #293
