### ISSUE TITLE
densitySurfaceDisplaced not used

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#315]
A lot of code and presumably computing time goes into computing `densitySurfaceDisplaced` for KPP, but then this field is never used:
```
$ grep -r densitySurfaceDisplaced
src/core_ocean/shared/mpas_ocn_diagnostics.F:           layerThickness, zMid, zTop, densitySurfaceDisplaced, density, &
src/core_ocean/shared/mpas_ocn_diagnostics.F:      type (field2DReal), pointer :: densitySurfaceDisplacedField, thermalExpansionCoeffField, salineContractionCoeffField
src/core_ocean/shared/mpas_ocn_diagnostics.F:      call mpas_pool_get_field(scratchPool, 'densitySurfaceDisplaced', densitySurfaceDisplacedField)
src/core_ocean/shared/mpas_ocn_diagnostics.F:      call mpas_allocate_scratch_field(densitySurfaceDisplacedField, .true., .false.)
src/core_ocean/shared/mpas_ocn_diagnostics.F:      densitySurfaceDisplaced => densitySurfaceDisplacedField % array
src/core_ocean/shared/mpas_ocn_diagnostics.F:                                         densitySurfaceDisplaced, err, thermalExpansionCoeff, salineContractionCoeff, &
src/core_ocean/shared/mpas_ocn_diagnostics.F:      call mpas_deallocate_scratch_field(densitySurfaceDisplacedField, .true.)
src/core_ocean/Registry.xml:		<var name="densitySurfaceDisplaced"
```
This field and all associated code for computing the EOS in `'surfaceDisplaced'` mode should be removed.

**Comment by xylar** [comment]
@vanroekel, you had brought this to my attention.  Feel free to do this clean up if you have time.  I'll try to get to it at some point in the not too distant future if you don't.  It's dumb to be implementing functionality for new EOSes that we don't use...

**Comment by philipwjones** [comment]
In older versions of KPP, this was used for surface buoyancy forcing and for the BL depth, but if it's not used anymore for those, would certainly be great to remove another bit of complexity from EOS.
