### ISSUE TITLE
MPAS-A random failures with PGI 12.5 compiler.

### ISSUE THREAD

**Issue by hrwinterbottom** [MPAS-Dev/MPAS-Model#4]
To whom it may concern:

I believe there to be an issue with MPAS-A atmosphere core executables built using PGI 12.5. There currently exist issues with MPAS-O, using PGI 12.5, and PGI 12.5 is thus unsupported by MPAS-O (as per Doug Jacobsen). The PGI bug reports can be found here: http://www.pgroup.com/support/release_tprs_2012.htm. The specific issue for MPAS-O is:

"Wrong answers when "transpose(derc)" is passed to matmul
Corrected the handling of matmul when the first argument is a transpose of a non-square matrix"

MPAS-A would (seemingly inexplicably and randomly) fail. My initial inclination was that either I was running into CFL issues and/or my vertical velocities were too large thus causing the model to segmentation fault. I reduced my timestep, for a 60-km MPAS-A mesh, from the default 180.0 seconds and test again. In some of these instances, the experiment would run to completion or it would simply run longer into it's respective forecast before again failing. I also changed the config_zd and config_xnutr values from the default 22000.0 and 0.2, respectively to 5000.0 and 1.0, respectively. Again, in some instances these experiments would run either to completion and/or just longer. 

After speaking with Doug Jacobsen regarding some issues with MPAS-O, I decided to build MPAS-A with PGI 13.2-0 (which is the latest PGI compiler available on the NOAA Jet machines). So far, all experiments which had failed previously have completed successfully -- using the default timestep (180 seconds) and config_zd and config_xnutr values. Whether the MPAS-O and MPAS-A issues are due to the same PGI bug is currently unknown to me.  

It should be noted that I _DID NOT_ rebuild PIO and PNETCDF with the latest available PGI compiler. 

Regards,

Henry Winterbottom

**Comment by mgduda** [comment]
@hrwinterbottom Thanks very much for this. It's good to know that the issue seemed related to the PGI 12.5 compilers. Since this issue is almost 5 years old, I'll go ahead and close it.
