### ISSUE TITLE
Problems in Compiling MPAS

### ISSUE THREAD

**Issue by yuyangyang0709** [MPAS-Dev/MPAS-Model#408]
When I use the command "make gfortran CORE=atmosphere", there will be a compilation error when complie the pio_test.
The error messages are as follow:

************ ERROR ************
Failed to compile a PIO test program
Please ensure the PIO environment variable is set to the PIO installation directory

Then, I tried compiling this program use the command:
mpif90 pio2.f90 -I/home/lulv/yuyy/software/pio/usr/local/include -L/home/lulv/yuyy/software/pio/usr/local/lib -o pio2.out

Compilation of MPAs failed. The error messages are:
_IO_OFFSET_KIND = PIO_OFFSET_KIND; integer, parameter :: MPAS_INT_FILLVAL = PIO
1
Error: Parameter 'pio_fil' at (1) has not been declared or is a variable, which does not reduce to a constant expression
Error: Unexpected end of file in 'pio2.f90'

Is there a problem with the ParallelIO installation?  I would appreciate it if you could reply me. Thank you.

**Comment by mgduda** [comment]
Could you post this question to the MPAS-Atmosphere support forum at https://forum.mmm.ucar.edu/ ? Ideally, GitHub Issues for the MPAS-Model repository are reserved for tracking specific issues with the MPAS code itself. For general help with MPAS-Atmosphere, the aforementioned forum is a good place to start.
