### ISSUE TITLE
hurricane test cases link to non-existent jigsaw_driver.m

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#431]
The test cases:
```
ocean/hurricane/USDEQU120at30cr10rr2/
ocean/hurricane/USDEQU60at15cr5rr1/
```
link to a non-existent Matlab driver script that we no longer support:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/hurricane/USDEQU120at30cr10rr2/build_mesh/config_base_mesh.xml#L5
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/hurricane/USDEQU60at15cr5rr1/build_mesh/config_base_mesh.xml#L5
These should be removed.

**Comment by pwolfram** [comment]
@xylar, I believe this has been resolved.  If you agree, can you please close?
