### ISSUE TITLE
Should Redi term 1 (horizontal del2) be untapered?

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Model#434]
The Redi mixing that I just merged in PR #280 tapers all terms in the vertical the same way. I learned today that MOM keeps the horizontal del2 (term 1) on at all layers. That would be an easy change. Should I change term 1 to not be tapered?

**Comment by vanroekel** [comment]
@mark-petersen I believe term1 is already untapered.  If I look here

https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_tracer_hmix_redi.F#L187

The flux_term is not multiplied by any slope and will not be tapered, or at least that is how I read the code.  Let me know if I'm missing something.

**Comment by mark-petersen** [comment]
This issue is old. A lot of tapering work has been done on Redi this year, so comment no longer applies.
