### ISSUE TITLE
Topography smoothing

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#436]
I'm concerned that we are not performing an adequate level of topography smoothing in MPAS-Ocean `global_ocean` configurations.  As an example, see bathymetry plot in #433.

I think it would be appropriate to do at least a few iterations of nearest-neighbor smoothing (with weights TBD) as part of initialization.  The step currently called smoothing:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/mode_init/Registry_global_ocean.xml#L178-L181
is actually just filling in holes in topography:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/mode_init/mpas_ocn_init_global_ocean.F#L976-L1007
which, while important, is not what I would think of when setting  the flag `config_global_ocean_smooth_topography`.

Given that I'm introducing a new bathymetry and ice draft for E3SM Cryosphere simulations, now might be the right time to talk about this issue.

**Comment by xylar** [comment]
@mark-petersen, @vanroekel, @maltrud, @milenaveneziani, Do you have thoughts on this?

**Comment by milenaveneziani** [comment]
By looking at the bathymetry plot that you pointed us to, I agree that it would be good to get rid of those isolated blue cells.
For my own indoctrination, could you please say how you obtained that bathymetry plot? I assume it comes as part of jigsaw, after the mesh has been created and while adding a land-mask/bathymetry before creating the initial condition?

**Comment by xylar** [comment]
> For my own indoctrination, could you please say how you obtained that bathymetry plot? I assume it comes as part of jigsaw, after the mesh has been created and while adding a land-mask/bathymetry before creating the initial condition?

It's `bottomDepth` from `initial_state.nc` the `initial_state` step of each test case.  It's from COMPASS but not related to Jigsaw.

**Comment by milenaveneziani** [comment]
great, thanks.

**Comment by milenaveneziani** [comment]
Here are some plots of bottom depth for the EC60to10v3. You can see some isolated pixels with fairly different values with respect to their surroundings, even using the lower resolution bathymetry:

![DepthSH_oEC60to30v3](https://user-images.githubusercontent.com/8237579/73310009-a1211100-41e0-11ea-9ce9-9d425401ddb7.png)
![DepthGlobal_oEC60to30v3](https://user-images.githubusercontent.com/8237579/73310007-a1211100-41e0-11ea-83cd-6efb8e18a640.png)

**Comment by xylar** [comment]
@milenaveneziani, just realized I never responded.  Thanks for these plots!  Yes, I would expect to see noise, including isolated island-like features in the low res v3 configuration, too.  That topography is also unsmoothed.

**Comment by pwolfram** [comment]
@xylar, this is for discrete, on MPAS mesh nearest-neighbor smoothing, correct?

**Comment by xylar** [comment]
@pwolfram, that's correct.  First, we bilinearly interpolate bathymetry to the MPAS grid at cell centers. 
 Then, the idea is to do some number of iterations of smoothing where the bathymetry value for the cell gets averaged with the mean of its neighboring cellsOnCell with a weighting of 0.9 for the cell itself and 0.1 for the mean of cellsOnCell.  The weights and the number of iterations are namelist options.  The default in this PR is zero iterations (no smoothing) for runs without ice-shelf cavities and 6 iterations for runs with ice shelf cavities.

**Comment by xylar** [comment]
This was implemented in #440
