### ISSUE TITLE
Remove basemap dependency

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#439]
The `basemap` package is no longer being maintained (see https://matplotlib.org/basemap/users/intro.html#deprecation-notice) and is becoming increasingly hard to install along with other conda packages (notably `proj` and `pyproj`). 

I would like to remove it from `compass`.  It is currently used  in the following locations:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py#L19
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py#L895-L896
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/hurricane/interpolate_time_varying_forcing.py#L11
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/hurricane/interpolate_time_varying_forcing.py#L99-L129

I think it should be possible to use `cartopy` for this plotting instead.

**Comment by xylar** [comment]
@sbrus89 (cc @pwolfram), would you be willing to help with this?  It looks like maybe the current usage of basemap is in code you wrote.

**Comment by sbrus89** [comment]
@xylar, sure. I'd be happy to help. Sounds like moving to `cartopy` is the way to go.

**Comment by pwolfram** [comment]
@xylar, I believe we've purged this issue on our coastal branch.  Can we please close?

**Comment by xylar** [comment]
I don't believe this has made it to `ocean/develop` yet, for example:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS/coastal_tools.py#L19

@mark-petersen, since you aren't ready to merge `ocean/coastal` to `ocean/develop` how can we at least get #441?

**Comment by xylar** [comment]
Addressed by #441
