### ISSUE TITLE
LANL IC compass instruction broken

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Model#475]
Current approach to load python for compass via

```
source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/etc/profile.d/conda.sh
conda activate compass_py3.7
```

in the file `https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/README_ocean.md` appears to no longer work.

**Comment by pwolfram** [comment]
Following posting this I got a browser refresh for new instructions and found that use of 

`source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/load_latest_compass.sh ` 

lacks `mpl_toolkits.basemap`, which is used in a variety of scripts.

Is there a reason this has been removed from COMPASS, if only as a deprecated feature?

**Comment by pwolfram** [comment]
See  #439

**Comment by xylar** [comment]
@pwolfram, the instruction you list above no longer appears in the file you link to:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/README_ocean.md

This was already fixed in https://github.com/MPAS-Dev/MPAS-Model/pull/462

Perhaps you are looking at an old branch?

**Comment by xylar** [comment]
Okay, I see that you now notice this.

**Comment by pwolfram** [comment]
Somehow my browser didn't refresh, it must have had the cached data.  Sorry for the trouble here.  We just had some scripts we were using in https://github.com/MPAS-Dev/MPAS-QuickViz/ that broke as a consequence of the environment change.

**Comment by xylar** [comment]
You really should switch to `cartopy`.  We have a PR for your to review to do this in compass (only coastal is using basemap at the moment): https://github.com/MPAS-Dev/MPAS-Model/pull/441

Please merge that ASAP.

I don't intend to make the COMPASS environment support MPAS-QuickViz, so I'm sorry that things are breaking there but you need to create your own conda enviornment that is compatible if so.

**Comment by xylar** [comment]
Also, I am getting sick and therefore grumpy.  Sorry for my tone, but hopefully that explains something...

**Comment by xylar** [comment]
I'm going to close this because I don't think it's a COMPASS or MPAS-Model issue.  Reopen and rename if you disagree.

**Comment by pwolfram** [comment]
I agree, thanks @xylar.
