### ISSUE TITLE
Field memory deallocation error with XL compilers

### ISSUE THREAD

**Issue by mgduda** [MPAS-Dev/MPAS-Model#481]
With the XL 16.1.1-5 compilers, a memory deallocation error is generated at run-time in the `mpas_field_routines` module:
```
"mpas_field_routines.F", line 1981: 1525-109 Error encountered while attempting to deallocate a data object.  The program will stop.
```

This issue was first noted by @amametjanov in the discussion on PR #367 .

**Comment by mark-petersen** [comment]
Fixed by #578.
