### ISSUE TITLE
PGI build of ocean on summit fails with bad dependency

### ISSUE THREAD

**Issue by philipwjones** [MPAS-Dev/MPAS-Model#488]
Build of latest ocean/develop is failing on Summit with PGI19.9, claiming a weird dependency:
PGF90-F-0004-Unable to open MODULE file cvmix_background.mod (mpas_subdriver.F: 14) 
where no such dependency should exist. While this might appear to be a compiler issue, a build of ocean/develop from ~week ago builds fine with this same compiler. 

Trying to narrow down further...

**Comment by jonbob** [comment]
@philipwjones - we just moved the cvmix and bgc codes to be submodules inside maps-ocean, so I'm guessing it's related to that. You'll have to update the submodules now, even in standalone. And in E3SM, you have to add a --recursive flag to the submodule update command. Because now we have submodules having submodules -- where will it ever stop??

**Comment by philipwjones** [comment]
@jonbob - yeah, I had already done that. When you forget to do that, you get a whole different error that's much clearer. But the cvmix connection is suspicious.

**Comment by jonbob** [comment]
That it is... Otherwise it does look like a compiler error, finding a bad dependency.

**Comment by philipwjones** [comment]
Looks like the submodule commit did indeed cause this, though still haven't identified what specifically is happening.

**Comment by philipwjones** [comment]
Ok, found the problem. Since the path to cvmix changed a little with the change to submodules, there's a hard-wired path in the build_options.mk that needs to be updated. Will submit a PR in a little bit. Not sure how the current version works on other machines...

**Comment by jonbob** [comment]
@philipwjones - thanks for tracking that down. I never use the standalone model so I have no clue...

**Comment by mark-petersen** [comment]
Fixed by #494.
