### ISSUE TITLE
link in test cases to load_compass_env.bash

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#490]
@sbrus89 requested a way to link to [load_compass_env.bash](https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/load_compass_env.bash) within a test case so this file can be sourced more easily to run the test case with the right environment.

**Comment by xylar** [comment]
We currently have the ability to create symlinks in COMPASS only at the level of steps within a test case, not in the main test case directory where the highest level `run.py` driver scrip is found.  Thus, this would require changes to `setup_testcase.py`.

It's not clear to me how best to do this.  Do we want to:
* hard code a link to `load_compass_env.bash` each time a drive script is created?
* modify all XML files for driver scripts to add a link (after modifying `setup_testcase.py` to support symlinks at the driver-script level)?
* something else?

**Comment by xylar** [comment]
A few other things to discuss that are semi-related:
* `load_compass_env.bash` should probably be renamed from `bash` to just `sh` since that's what we (and conda) do elsewhere.
* we probably want this script in `develop` so `landice` and other components can use it, too.

**Comment by xylar** [comment]
cc @sbrus89, @mark-petersen and @pwolfram

**Comment by sbrus89** [comment]
My initial thought would be to hard code the link (first option), but add a CL argument to setup_testcase.py so that everything behaves normally (i.e. no link) unless it is specified.

**Comment by xylar** [comment]
Sounds like a nice idea.

**Comment by xylar** [comment]
Addressed in #492
