### ISSUE TITLE
Problems compiling MPAS with PGI

### ISSUE THREAD

**Issue by Enea2301** [MPAS-Dev/MPAS-Model#509]
Hi! I've been recently trying to compile MPAS, as I'm into model forecasting (I've worked with WRF very often).

I'm trying to compile MPAS with PGI compilers (as I had done previously with WRF), but a problem appears while compiling MPAS init_atmosphere.

-Computer SO: Ubuntu 20.04 (changed recently because of better support for my CPU, which is Zen 2 architecture)
-Compiler version: 19.10 (community edition). Using no-llvm.
-MPI: the one provided with PGI (OpenMPI 3.x)
-NetCDF: 4.6.1 and Fortran 4.5.2. Compiled with PGI for WRF before.
-PnetCDF: 1.12.1. Compiled with PGI apparently without problems.
-PIO: 1.7.1

-Makeline used: make pgi CORE=init_atmosphere

This is the problem that is returned when trying to compile:

> make[4]: se entra en el directorio '/home/roberto/MPAS/MPAS-Model-7.0/src/driver'
rm -f mpas_subdriver.o mpas_subdriver.mod
mpif90 -D_MPI -DCORE_INIT_ATMOSPHERE -DMPAS_NAMELIST_SUFFIX=init_atmosphere -DMPAS_EXE_NAME=init_atmosphere_model -DMPAS_NATIVE_TIMERS -DMPAS_GIT_VERSION=unknown -O3 -byteswapio -Mfree -r8 -c mpas_subdriver.F -I/home/roberto/MPAS/MPASlib/pio/include -I/home/roberto/Build_WRF/LIBRARIES/netcdf/include -I/home/roberto/MPAS/MPASlib/pnetcdf/include -I/home/roberto/MPAS/MPASlib/pio/include -I/home/roberto/Build_WRF/LIBRARIES/netcdf/include -I/home/roberto/MPAS/MPASlib/pnetcdf/include -I../framework -I../operators -I../core_init_atmosphere -I../external/esmf_time_f90
rm -f mpas.o mpas.mod
mpif90 -D_MPI -DCORE_INIT_ATMOSPHERE -DMPAS_NAMELIST_SUFFIX=init_atmosphere -DMPAS_EXE_NAME=init_atmosphere_model -DMPAS_NATIVE_TIMERS -DMPAS_GIT_VERSION=unknown -O3 -byteswapio -Mfree -r8 -c mpas.F -I/home/roberto/MPAS/MPASlib/pio/include -I/home/roberto/Build_WRF/LIBRARIES/netcdf/include -I/home/roberto/MPAS/MPASlib/pnetcdf/include -I/home/roberto/MPAS/MPASlib/pio/include -I/home/roberto/Build_WRF/LIBRARIES/netcdf/include -I/home/roberto/MPAS/MPASlib/pnetcdf/include -I../framework -I../operators -I../core_init_atmosphere -I../external/esmf_time_f90
make[4]: se sale del directorio '/home/roberto/MPAS/MPAS-Model-7.0/src/driver'
make[3]: se sale del directorio '/home/roberto/MPAS/MPAS-Model-7.0/src/driver'
mpif90 -O3 -o init_atmosphere_model driver/*.o -L. -ldycore -lops -lframework -L/home/roberto/MPAS/MPASlib/pio/lib -lpio -L/home/roberto/Build_WRF/LIBRARIES/netcdf/lib -lnetcdff -lnetcdf -L/home/roberto/MPAS/MPASlib/pnetcdf/lib -lpnetcdf -I./external/esmf_time_f90 -L./external/esmf_time_f90 -lesmf_time
driver/mpas_subdriver.o: en la función `mpas_subdriver_mpas_init_':
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x546): reubicación truncada para ajustar: R_X86_64_32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x56f): reubicación truncada para ajustar: R_X86_64_PC32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x5de): reubicación truncada para ajustar: R_X86_64_PC32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x5ff): reubicación truncada para ajustar: R_X86_64_32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x604): reubicación truncada para ajustar: R_X86_64_32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x615): reubicación truncada para ajustar: R_X86_64_PC32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x626): reubicación truncada para ajustar: R_X86_64_PC32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x638): reubicación truncada para ajustar: R_X86_64_PC32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x64e): reubicación truncada para ajustar: R_X86_64_32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x653): reubicación truncada para ajustar: R_X86_64_32 contra el símbolo `_mpas_subdriver_0_' definido en la sección COMMON en driver/mpas_subdriver.o
/home/roberto/MPAS/MPAS-Model-7.0/src/driver/./mpas_subdriver.F:141:(.text+0x65d): se omitieron desbordamientos de reubicación adicionales de la salida
make[2]: *** [Makefile:18: mpas] Error 2
make[2]: se sale del directorio '/home/roberto/MPAS/MPAS-Model-7.0/src'
make[1]: *** [Makefile:780: mpas_main] Error 2
make[1]: se sale del directorio '/home/roberto/MPAS/MPAS-Model-7.0'
make: *** [Makefile:72: pgi] Error 2

Please note that in I tried with Makefile by default (pgf90 and pgcc) and changing fortran compiler to the one I used to build everything (pgfortran and pgcc), and same output was thrown.

I'm not used to fortran language or to almost any language, so I'm not able to research it on my own more than on the surface.

Thanks for your help,
Roberto

**Comment by mgduda** [comment]
My guess is that this is an issue either with the compiler or with one of the supporting libraries, and not necessarily with the MPAS code itself. Could you post this to the MPAS-Atmosphere section of the support forum at https://forum.mmm.ucar.edu/ ?

If it turns out that there is an issue with the MPAS code itself, we can follow-up on this GitHub issue; otherwise, this sounds like it may be a model support question and not a code issue.

**Comment by Enea2301** [comment]
Sure! I'll post there and see if it gets resolved. Thanks for your help!
