### ISSUE TITLE
Building with system-installed NetCDF libraries on Linux

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#51]
In setting up MPAS on my laptop (Ubuntu 18.04), I decided to avoid the hassle of compiling NetCDF libraries myself and used the default versions that come with the Ubuntu package manager.  This worked well except one hiccup.  The library files are placed in:
```
/usr/lib/x86_64-linux-gnu/
````

I was able to get MPAS-O to build by setting
```
export MPAS_EXTERNAL_LIBS='-L/usr/lib/x86_64-linux-gnu/ -lnetcdff'
```
but this seems to somewhat defeat purpose of all the fancy automation in the Makefile and it's also not very intuitive for users.

Might it be worth supporting separate `$NETCDF_INC` and `$NETCDF_LIB` variables, perhaps in addition to the current `$NETCDF`?

Also partly wondering if others have run into this problem (or something similar).

**Comment by mark-petersen** [comment]
This issue has gone stale.
