### ISSUE TITLE
Errors in CUSP 12 spin-up

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#525]
CUSP8 and CUSP12 stage `spin_up/test_final_settings` is misconfigured.:
```
config_run_duration = '00-01-00_00:00:00'
```
But the last restart file is:
```
restart.0001-01-07_00.00.00.nc
```
This is not compatible with how MPAS handles restarts: there would need to be a restart file at an even month boundary for this to work.

**Comment by xylar** [comment]
I'm going to see if similar issues emerge elsewhere and then fix this in #523

**Comment by xylar** [comment]
Update: this is really beyond #523 and needs someone to figure out what is actually useful for the CUSP spin-up.  For example, the `timeSeriesMonthlyOutput` analysis is turned on but the output is also not being produced.  And monthly output is only going to be useful if this is running for a second month, following a month of spin-up.  @mark-petersen, I'm going to assign this to you but please let me know who "owns" this test case and should fix this.

**Comment by xylar** [comment]
I suspect CUSP8 will have the same issues, since the various `prep_spin_up` stages have been modified in #445 but the final stage of that test case was also not updated.

**Comment by mark-petersen** [comment]
Thanks for pointing this out. I will make modifications in https://github.com/MPAS-Dev/MPAS-Model/pull/523.

**Comment by xylar** [comment]
Renaming since CUSP 8 has been removed.

**Comment by mark-petersen** [comment]
This now applies to `WC12` and `WC14`. I double checked, and in both the run duration is divisible by the restart frequency. For example, here
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/global_ocean/WC14/spin_up/config_test_final_settings.xml#L14
and here
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/global_ocean/WC14/spin_up/config_test_final_settings.xml#L32
