### ISSUE TITLE
A template for high-frequency output contains time monthly output

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#534]
The following file was added in #104, seemingly as a placeholder to be modified (but if so it never got modified):
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/global_ocean/template_high_frequency_output.xml
This file should be removed or made useful.  It is currently not used.

**Comment by mark-petersen** [comment]
That one was added by mistake. This one is used and correct:
```
testing_and_setup/compass/ocean/templates/analysis_members/high_frequency_output.xml
```
I'll remove that other one when I get a chance.

**Comment by xylar** [comment]
Replaced by https://github.com/MPAS-Dev/compass/issues/9
