### ISSUE TITLE
The MPI_Comm_f2c() function was called before MPI_INIT was invoked.

### ISSUE THREAD

**Issue by zredb** [MPAS-Dev/MPAS-Model#554]
Hello,
   I'm new to MPAS, I followed the "https://www2.mmm.ucar.edu/projects/mpas/tutorial/Boulder2019/index.html" page to build and run tutorial, but I get message as below:
*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[mpas:50242] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

anyone can give some suggestion?

Additionally please enter this information if applicable:
 - Compiler and version :gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
 - MPI implementation and version : mpich-3.3.1
 - NetCDF version : netcdf-c-4.7.4
 - Parallel NetCDF version : pnetcdf-1.11.2
 - Parallel IO version : pio-2.5.0
 - Output of `uname -a` :
Linux mpas 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - The make line used to build the executable
make -j4 gfortran CORE=init_atmosphere PRECISION=single USE_PIO2=true
 - The line used to run the executable
 ./init_atmosphere_model
 - Test case used

**Comment by mgduda** [comment]
@zredb Could you post this question to the MPAS-Atmosphere section of the support forum at https://forum.mmm.ucar.edu/ ? If we determine that there is actually an issue with the code itself, then we can open a GitHub Issue; until then, the support forum would be a better venue for requesting help.

**Comment by zredb** [comment]
hello @mgduda,
     Thank you for you reply. After several compilation attempts, the problem has been solved.
