### ISSUE TITLE
Incorrect triangle or kite area for edges

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#558]
Following up on #556, there are several places where edge areas (either for the edge triangles that make up a cell or the kite that represents the "domain" of an edge) are missing a factor of 0.5 or sometimes even 0.25.  

These don't matter because the factor of 2 error is in both the numerator and the denominator, but it's confusing:
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/analysis_members/mpas_ocn_high_frequency_output.F#L518
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/analysis_members/mpas_ocn_high_frequency_output.F#L520
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/analysis_members/mpas_ocn_high_frequency_output.F#L524
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/analysis_members/mpas_ocn_high_frequency_output.F#L528

In global stats, `areaEdge` is meant to be the sum of the two triangles for a given edge (`0.5*dcEdge*dvEdge`) but it is missing the factor of 0.5.  This means that global inetgrals of edge quantities are a factor of 2 too large.  Averages will be correct because the factor is again in numerator and denominator:
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/analysis_members/mpas_ocn_global_stats.F#L406
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/analysis_members/mpas_ocn_global_stats.F#L1071

It looks like an `areaEdge` that is 4 times too large is getting used to compute `k33`, but this same area is used to compute the total volume used to normalize `k33`, so the error doesn't matter:
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_gm.F#L303

Later in the same routine, `areaEdge` is computed correctly, which makes the first instance all the more confusing:
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_gm.F#L560

In diagnostics, I'm going to assume that several confusing factor cancel out and the calculation of KE on cell and vertex centers is right:
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_diagnostics.F#L372-L377
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_diagnostics.F#L436
* There's a factor of 0.25 to convert `dcEdge*dvEdge` into the area of an edge triangle
* There's a factor of 0.5 for the definition of KE
* There's a factor of 2 because we are only adding the normal velocity, not the tangential velocity (and I vaguely recall from one of the Ringler papers that this just magically works out to a factor of 2).

The factor of 2 definitely matters here, though I don't think we run with the MPAS (as opposed to the CVMix) Richardson mixing anymore (see #557).
* https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_vmix_coefs_rich.F#L565-L566

**Comment by mark-petersen** [comment]
@xylar thanks for writing up this list with an issue. #556 should be corrected as an isolated bug, but I will make a PR to fix these too.

**Comment by xylar** [comment]
Please see my comment on #556. I do think we want to correct all of them, even the ones that "don't matter". Using incorrect areas clearly leads to misconceptions that propagate to other parts of the code.
