### ISSUE TITLE
COMPASS: rename e3sm_coupling and move it to be its own test

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#585]
I would like to move the `e3sm_coupling` step to be its own "test" (at the same level as `init` and `spin_up`) in each `global_ocean` test case.

My reasoning for renaming is that we want to make clear that, once this code is more robust, it will generate an E3SM ocean (and possibly sea-ice, though that can be part of this discussion) initial condition.  I don't have a great suggestion for the new name but something like `e3sm_ocean_init`.

My reasoning for moving it to its own "test" is:
* it should be able to be run automatically, e.g. as part of a regression suite so we can check for unwanted changes
* it should be clear that this stage needs to run after `init` and typically also after `spin_up`.  If it is its own test, we can use a `prerequisite` tag to indicate this, see #559 and #560.
* it shouldn't be buried

**Comment by xylar** [comment]
As part of this work, I would take out the steps that involve other E3SM components (e.g. generating mapping files to atmosphere and land grids).  This work will need to move to a different set of scripts, a different repo, and a different set of tools that is still in the planning stage.

**Comment by xylar** [comment]
@jonbob, @vanroekel, @maltrud and @mark-petersen, I'd appreciate your thoughts before I start on this.

**Comment by mark-petersen** [comment]
Yes, I agree that moving `e3sm_coupling` to a step after `spin_up` and at the same level, as it's own test case, makes more sense than where it is hidden now. Thanks for thinking of it. 

I don't think we should remove mapping file capability until it is available and tested in another process.

I think it still makes sense to create the sea ice initial condition here in COMPASS, since the sea ice mesh is the same MPAS mesh and it is a convenient place to do it. We will also be adding special graph files for load balancing and potentially remove low latitude cells, and I think those steps make sense in this COMPASS system. So rather than name it `e3sm_ocean_init` I would say `e3sm_init`.

**Comment by xylar** [comment]
> I think it still makes sense to create the sea ice initial condition here in COMPASS, since the sea ice mesh is the same MPAS mesh and it is a convenient place to do it.  We will also be adding special graph files for load balancing and potentially remove low latitude cells, and I think those steps make sense in this COMPASS system.

Could you elaborate on why you think these make more sense in COMPASS than in a repo under E3SM-Project?  It seems to me that this would be equally convenient to do in the "other" system.  And given that MPAS-Seaice has opted out of COMPASS, it seems like its initialization shouldn't be tied to COMPASS if there is an alternative.  But I'm open to understanding why it's easier to keep it here.

> So rather than name it `e3sm_ocean_init` I would say `e3sm_init`.

I'm definitely not good with this.  It implies basically the same thing as the old name, namely that it provides everything you need for an E3SM initial condition.  It should be clearer that this is just ocean (and maybe sea ice).

**Comment by jonbob** [comment]
@xylar - I agree with your proposed changes. I think the renaming is consistent with ongoing work in other parts of the system, as is removing the steps that involve other E3SM components. Please let me know if I can help in any way.

**Comment by xylar** [comment]
As part of this work, I will add `hostname` to the metadata as requested by @milenaveneziani: https://github.com/MPAS-Dev/MPAS-Model/pull/584#issuecomment-637667560

I will remove the runoff metadata from COMPASS because we have decided that will be handled in the new repo in E3SM-Project, so we won't necessarily even know the approach at the COMPASS stage.

**Comment by mark-petersen** [comment]
@xylar after some thought I can see the advantages of `e3sm_ocean_init` to clearly label and partition the ocean part of this process. Please proceed, as you proposed in the top description.

**Comment by vanroekel** [comment]
@xylar I think these are good changes and in line with what we are slowly working toward elsewhere.  I also agree we go with e3sm_ocean_init

**Comment by xylar** [comment]
Moved to https://github.com/MPAS-Dev/compass/issues/11
