### ISSUE TITLE
local ocean allocatable arrays are wrong size

### ISSUE THREAD

**Issue by philipwjones** [MPAS-Dev/MPAS-Model#597]
In some of the recently introduced ocean changes, local allocatable arrays were only allocated up to nCellsAll (formerly nCellsSolve). However, adjacency indices in cellsOnCell, etc. use nCellsAll+1 for non-existent neighbors. This results in out-of-bounds indexing and these arrays need to be resized.

So far, this is seen in the new ocean mesh module and the ocn_tracer_advection_mono module.

**Comment by mark-petersen** [comment]
I read that `fixes XXX` in the commit message only closes an issue once it gets to master. So we will need to close these by hand when merging to `ocean/develop`. 

Fixed by #598.
