### ISSUE TITLE
Bad `bottomDepth` data in initial_state.nc for EC60to30 on Cori

### ISSUE THREAD

**Issue by mattdturner** [MPAS-Dev/MPAS-Model#678]
When attempting to run the EC60to30 test via COMPASS, there appears to be incorrect data being written to the `initial_state.nc` file on Cori (process described below).  When running the same process on Grizzly, the inputs look correct.

On Cori, the following steps were taken to generate the `initial_state.nc` file:
Currently loaded conda env: `compass_0.1.9         *  /global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/compass_0.1.9`
Current git hash: `730d7b9253895e74c162d65a83b462e9f03b79ad`
```
[10:19]mturner@cori03  (ocean/develop):make clean CORE=ocean
[10:25]mturner@cori03  (ocean/develop):make intel-nersc CORE=ocean -USE_PIO2=true -j 16 OPENMP=true
<cd to compass directory>
[10:25]mturner@cori03  (ocean/develop):./setup_testcase.py --config_file general.config.ocean.cori --work_dir $WORKDIR/runs/semi_implicit_08312020 --model_runtime runtime_definitions/srun.xml -n 71
<test 71: -o ocean -c global_ocean -r EC60to30 -t init>
[10:26]mturner@cori03  (ocean/develop):cd $WORKDIR/runs/semi_implicit_08312020/ocean/global_ocean/EC60to30/init/
[10:27]mturner@cori03 :./run.py  <on interactive node>
```

After the script ends (successfully), I looked at the `initial_state.png` file.  It shows the following:
![initial_state](https://user-images.githubusercontent.com/8278916/91748318-09701080-eb7d-11ea-9a15-4b3c50a26b7d.png)

A plot of the corresponding `bottomDepth` field shows
![bottomDepth_paraview](https://user-images.githubusercontent.com/8278916/91748376-20aefe00-eb7d-11ea-88f9-d3b4e99ba817.png)

Modules used to compile / run:
```
[10:29]mturner@cori03  (ocean/develop):module list
Currently Loaded Modulefiles:
  1) modules/3.2.11.4                                 16) dvs/2.12_2.2.157-7.0.1.1_9.2__g083131db
  2) altd/2.0                                         17) alps/6.6.58-7.0.1.1_6.5__g437d88db.ari
  3) cray-mpich/7.7.10                                18) rca/2.2.20-7.0.1.1_4.48__g8e3fb5b.ari
  4) intel/19.0.3.199                                 19) atp/2.1.3
  5) craype-haswell                                   20) PrgEnv-intel/6.0.5
  6) craype-network-aries                             21) cray-netcdf-hdf5parallel/4.6.3.2
  7) craype/2.6.2                                     22) cray-hdf5-parallel/1.10.5.2
  8) cray-libsci/19.06.1                              23) cray-parallel-netcdf/1.11.1.1
  9) udreg/2.3.2-7.0.1.1_3.33__g8175d3d.ari           24) git/2.21.0
 10) ugni/6.0.14.0-7.0.1.1_7.35__ge78e5b0.ari         25) cmake/3.14.4
 11) pmi/5.0.14                                       26) tmux/2.8
 12) dmapp/7.1.1-7.0.1.1_4.49__g38cf134.ari           27) pio/2.4.4-intel
 13) gni-headers/5.0.12.0-7.0.1.1_6.29__g3b1768f.ari  28) lapack/3.9.0/intel19
 14) xpmem/2.2.20-7.0.1.1_4.11__g0475745.ari          29) metis/5.1.0
 15) job/2.2.4-7.0.1.1_3.37__g36b56f4.ari             30) allinea-forge/20.1-Suse-15.0-x86_64
```

**Comment by mattdturner** [comment]
I ran the same thing on Grizzly, and got the following `initial_state.png` figure:
![initial_state](https://user-images.githubusercontent.com/8278916/91748500-4e944280-eb7d-11ea-8671-7b0c382f9897.png)

So the issue appears to be Cori-specific.

**Comment by xylar** [comment]
Thanks @mattdturner.  It looks from your ParaView plot as if the bathymetery data is getting read with the wrong stride or something.  I'll try to figure it out.

We don't run COMPASS on Cori that often because of the long queue times so it hasn't got as much testing as other systems.

Just as a sanity check, did you load your modules and then load the `compass_0.1.9` environment or the other way around?  We've found on Grizzly that it's important to load `compass` first and then load the the system version of various libraries.  Python scripts will find the versions of the libraries from the conda environment as they need to but the compiled code will work with the system versions.  Just a thought...

**Comment by mattdturner** [comment]
My modules are loaded in the following order:
```
module load PrgEnv-intel
module load cray-mpich
module load craype-haswell
 
module load cray-netcdf-hdf5parallel
module load cray-hdf5-parallel
module load cray-parallel-netcdf
 
module load git
module load cmake
 
source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_compass.sh

module load metis
```

I can re-run after loading compass first, and report back.

**Comment by xylar** [comment]
Yes, please do that.  I don't know if it will make a difference but it would at least be safer in that order.

**Comment by mattdturner** [comment]
After loading the compass environment first, I still get the same histograms as listed in the initial comment.

**Comment by xylar** [comment]
Okay, thanks for ruling that out.  I'll take a look tomorrow.

**Comment by xylar** [comment]
@mattdturner, could you share your config file for COMPASS?  Specifically, I'd like so see where your initial conditions are being stored.  I suspect that one possibility is that the topography file is corrupted and needs to be deleted and downloaded again.  One way to tell is that the file date should be 25 Jan 2020 but if the file didn't download correctly, it may have the date that it was (partially) downloaded instead.  I experienced this and some related hanging when I tried to setup the run on Cori just now.

A solution to this would be to have a shared location for meshes, initial conditions and bathymetry data like we do on LANL IC.  I will set that up and bring all the data over from LCRC as soon as I can.

My test job is still in the queue so I'll let you know if I have better luck as soon as it runs.

**Comment by xylar** [comment]
Ah, I see that we do have such a location already:
```
/global/cfs/cdirs/e3sm/mpas_standalonedata/mpas-ocean/initial_condition_database
```
but it looks like the data there is pretty incomplete and should be copied wholesale from LCRC.

It does look like the topography file is incomplete and corrupt.  Here's what I see when I download it to my own directory:
```
-rw-rw----  1 xylar xylar 223M Jan 25  2020 ETOPO2v2c_f4_151106.nc
```
Here's what I see in the shared location:
```
-rw-rw-r-- 1 mpeterse e3sm     28M Dec  4  2019 ETOPO2v2c_f4_151106.nc
```

**Comment by xylar** [comment]
I am re-downloading all the data from `mpas_standalonedata` right now.  I will update when that's done.  I moved the previous `mpas_standalonedata` directory to `old_mpas_standalonedata` and will ask to have it removed by an E3SM admin once the new data is in place.

**Comment by xylar** [comment]
Here's the result of my test on Cori with my own version of the input data:
![initial_state](https://user-images.githubusercontent.com/4179064/91853076-f8e59600-ec61-11ea-9d32-882fffeb8824.png)
It seems to match the Grizzly results so I think the bad bathymetry file is the only problem.

**Comment by mattdturner** [comment]
Thanks @xylar for taking care of this so quickly.  It looks like the bad topography file was probably the culprit.

**Comment by mattdturner** [comment]
Using the updated bathymetry file, I was able to replicate the same `initial_state.png` file that you produced, which matches what I saw on Grizzly.  So I think this issue can be marked as resolved.

**Comment by xylar** [comment]
Great, I’ll go ahead and close this. Down the road, it would be great to improve COMPASS so it checks to make sure download files are complete but that’s kind of a project.
