### ISSUE TITLE
Online moc stream function AM unable to read regionGroupNames from COMPASS generated files

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Model#727]
Currently ```regionGroupNames``` and ```transectGroupNames``` are not being read from MOC_transect_mask files generated by COMPASS, in debugging it appears the issue is the name of the string length dimension.  Here is the nc header of a new file where regionGroupNames is not read
```
netcdf EC30to60E2r2_moc_masks_and_transects {
dimensions:
	nCells = 236853 ;
	nRegions = 4 ;
	nVertices = 482371 ;
	string64 = 64 ;
	nRegionGroups = 2 ;
	maxRegionsInGroup = 4 ;
	nEdges = 719506 ;
	nTransects = 4 ;
	maxEdgesInTransect = 1741 ;
	maxVerticesInTransect = 1742 ;
	nTransectGroups = 2 ;
	maxTransectsInGroup = 4 ;
```
Here is an old transect/mask header 
```
netcdf EC60to30v3_transect_masks {
dimensions:
	nCells = 235160 ;
	nVertices = 478835 ;
	nEdges = 714274 ;
	nTransects = 15 ;
	nTransectGroups = 2 ;
	maxTransectsInGroup = 15 ;
	maxCellsInTransect = 81 ;
	maxVerticesInTransect = 165 ;
	maxEdgesInTransect = 166 ;
	StrLen = 64 ;
```
If I take the new file and ncrename ```string64``` to ```StrLen``` regionGroupNames and transectGroupNames are able to be read by the online AM again.

**Comment by xylar** [comment]
Fixed in https://github.com/MPAS-Dev/MPAS-Tools/pull/367
