### ISSUE TITLE
Bugs in tracer advection code

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Model#732]
There are a few issues in the tracer advection code, both _mono and _std.

(1) If we look at vertOrder3 here

https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/shared/mpas_ocn_tracer_advection_mono.F#L663-L695

and compare this with Skamarock and Gassmann (2011), their equation 11
![Screen Shot 2020-10-27 at 12 55 12 PM](https://user-images.githubusercontent.com/13662545/97348382-adabc600-1853-11eb-8e7f-54fb7c186399.png)

there is a sign error on the term multiplying coef3rdOrder.  This occurs here and in vflux3 in the framework

(2) the third order and fourth order fluxes are not weighted by thickness.  This could lead to lower than expected accuracy in vertical advection

**Comment by mark-petersen** [comment]
On (2), see [comment on PR](https://github.com/MPAS-Dev/MPAS-Model/pull/738#discussion_r514760374). It is a linear interpolation, not a weighted average, so original is correct.

**Comment by vanroekel** [comment]
For both the original formulation is correct.  Closing this issue.  See discussion in #738 for further information.
