### ISSUE TITLE
PGI compiler chokes on array syntax in ocean tend_tracer routine

### ISSUE THREAD

**Issue by philipwjones** [MPAS-Dev/MPAS-Model#805]
In mpas_ocn_tendency.F and the tend_tracer routine, there is a loop over activeTracerNonLocalTend that causes the PGI compiler to die with the error:

/tmp/pgfortran0eVuCCLsnvvY.s: Assembler messages:
/tmp/pgfortran0eVuCCLsnvvY.s:2910: Error: operand out of range (0x0000000000008000 is not between 0xffffffffffff8000 and 0x0000000000007ffc)

This appeared during the switch from pointer retrieval to public array for some reason, but appears to be related to translating the array syntax in the problem loop. Replacing array syntax with an explicit loop eliminates the problem and a bug fix PR is on the way.

**Comment by mattdturner** [comment]
This was resolved in #806 .
