### ISSUE TITLE
An error occured when running MPAS-A

### ISSUE THREAD

**Issue by X1a0wu2** [MPAS-Dev/MPAS-Model#970]
Can't create the static file with the 60-3km mesh

At first, I rotated the mesh to the area I was interested in, and then generate the static field. The problem is when the file of the static field is generated to 1.04G, it stopped, the same situation happens with repeated runs

Additionally please enter this information if applicable:
 - Compiler and version     compiler/intel/2017.5.239
 - MPI implementation and version    mpi/intelmpi/2017.4.239
 - NetCDF version    mathlib/netcdf/intel/4.4.1
 - Parallel NetCDF version  mathlib/pnetcdf/intel/1.12.1
 - Parallel IO version    mathlib/pio/intel/2.5.1
 - Output of `uname -a`
 - The make line used to build the executable
 - The line used to run the executable
 - Test case used

**Comment by mgduda** [comment]
Please use the support forum at https://forum.mmm.ucar.edu/ to ask this question.
